version: "3"

services:
  overpass:
    image: ghcr.io/poibee/poibee-overpass:main
    container_name: poibee-overpass
  app:
    image: ghcr.io/poibee/poibee-app:main
    container_name: poibee-app
  busybox:
    # use: 'docker attach poibee-busybox'
    image: busybox:latest
    container_name: poibee-busybox
    stdin_open: true
    tty: true
