apiVersion: apps/v1
kind: Deployment
metadata:
  name: poibee-overpass
  namespace: poibee
  labels:
    app: poibee-overpass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poibee-overpass
  template:
    metadata:
      labels:
        app: poibee-overpass
    spec:
      containers:
        - image: ghcr.io/poibee/poibee-overpass:main
          imagePullPolicy: Always
          name: poibee-overpass
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: poibee-overpass
  namespace: poibee
  labels:
    app: poibee-overpass
spec:
  ports:
    - port: 3000
  selector:
    app: poibee-overpass
---
# https://kubernetes.github.io/ingress-nginx/examples/rewrite/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poibee-ingress-overpass
  namespace: poibee
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - poibee.de
      secretName: tls-secret-poibee-prod
  rules:
    - host: poibee.de
      http:
        paths:
          - pathType: Prefix
            path: /api/overpass(/|$)(.*)
            backend:
              service:
                name: poibee-overpass
                port:
                  number: 3000