replicaCount: 1

image:
  repository: ghcr.io/poibee/poibee-overpass
  pullPolicy: Always
  tag: "main"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

# https://kubernetes.github.io/ingress-nginx/examples/rewrite/
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: poibee.de
      paths:
        - path: /api/overpass(/|$)(.*)
          pathType: Prefix
  tls:
    - secretName: tls-secret-poibee-prod
      hosts:
        - poibee.de

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 50Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
