replicaCount: 1

image:
  repository: ghcr.io/poibee/poibee-app
  pullPolicy: Always
  tag: "92-migrate-ionic"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: poibee.de
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - secretName: tls-secret-poibee-prod
      hosts:
        - poibee.de

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
