name: Deploy by Helm

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  POIBEE_KUBECONF: ${{ secrets.POIBEE_KUBECONF }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          kubectl: '1.17.1'
          helm: '3.5.2'
      - run: |
          cd helm
          umask 066; echo "$POIBEE_KUBECONF" > local-kubeconf.conf
          export KUBECONFIG=local-kubeconf.conf
          helm -n poibee uninstall poibee-app-chart
          helm -n poibee install poibee-app-chart poibee-app/ --values poibee-app/values.yaml
          helm -n poibee uninstall poibee-overpass-chart
          helm -n poibee install poibee-overpass-chart poibee-overpass/ --values poibee-overpass/values.yaml
          helm -n poibee ls
